services:
  - type: web
    name: sarahfoundation
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py createsuperuser --noinput --username andy --email andy@gmail.com || true
    startCommand: gunicorn SarahFoundation.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: SarahFoundation.settings
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: ADMIN_PASSWORD
        value: andy12345
    autoDeploy: true
    healthCheckPath: "/"

databases:
  - name: sarahfoundation-db
    plan: free
