services:
  - type: web
    name: sarahfoundation
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn SarahFoundation.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: SarahFoundation.settings
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      # connects to the database service defined below 
      - key: DATABASE_URL
        fromDatabase:
          name: sarahfoundation-db
          property: connectionString
    autoDeploy: true
    healthCheckPath: "/"

databases:
  - name: sarahfoundation-db
    plan: free
